### ISSUE TITLE
Csv, xls, xlsx files not supported 

### ISSUE THREAD

**Issue by pochol** [nnhubbard/matrixupload2#10]
Hi,

Can you guys help me with this issue ? Maybe there is some way to upload those files through matrixupload2 to the Matrix. All set up in matrix on asset builder as suggested. Screenshots attached below.

<img width="1258" alt="screen shot 2016-11-18 at 17 01 58" src="https://cloud.githubusercontent.com/assets/5519468/20436510/c5a32724-adb0-11e6-8ba0-f8561edd5fb3.png">

<img width="809" alt="screen shot 2016-11-18 at 17 06 47" src="https://cloud.githubusercontent.com/assets/5519468/20436691/6e1ca57e-adb1-11e6-9f0c-ee43ead325d4.png">

Thanks,
Marcin

**Comment by nnhubbard** [comment]
`xls and xlsx` files are uploading correctly for me. Also, if you want to upload `.csv` files you need to add the `Text File` asset to the Asset Builder, since the `MS Excel Document` asset does not allow `.csv` files.

**Comment by pochol** [comment]
Thanks mate
