### ISSUE TITLE
Image upload progress stuck

### ISSUE THREAD

**Issue by StateLibraryofQueensland** [nnhubbard/matrixupload2#8]
Currently trying to implement this plugin and when uploading images, the image thumbnail shows on screen but the progress bar does not begin loading - it just stays at zero.

No commit/upload button appears, most likely because the upload function cannot complete.

I am using Squiz Matrix v4.18.4 - is this plugin only suitable for a more recent version of Squiz Matrix (i.e. version 5)?

**Comment by nnhubbard** [comment]
Default is to auto-upload rather than show the upload button. But you can change this in the options.

4.18.4 is totally fine.

What browser are you using? You need to be using a modern browser since they support upload progress.

**Comment by SLQ-CommWeb** [comment]
Hi Nic,
Was using Firefox version 29.0.1

Gosh, hope it works for IE11 then. Most of the clients will be using this browser unfortunately..

**Comment by nnhubbard** [comment]
Yes, IE11 will work. You will get an error if the browser is not compatible. 

Are you able to show me the page you are testing this on? Or, email me nic at zedsaid dot com.
